CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: auto
  ROOT: /mnt/RG/dataset/train
  TEST_SET: /mnt/RG/auto_train_files_with_gt.txt
  TRAIN_SET: /mnt/RG/auto_train_files_with_gt.txt
  NUM_CLASSES: 5
MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 1
  PRETRAINED: "pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar"
LOSS:
  USE_OHEM: True
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 400
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: false
  MULTI_SCALE: false
  IGNORE_LABEL: 255
  SCALE_FACTOR: 32
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
